name: Create Chrofil Release

on:
  push

permissions:
  contents: write

env:
  RELEASE_NAME: 'release/chrofil-latest.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create zip
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: '$RELEASE_NAME'
        path: './Chrofil_ext'
    - name: Update or add zip file
      uses: EndBug/add-and-commit@v9
      with:
        run: |
          git add $RELEASE_NAME
          git commit "Action: Update $RELEASE_NAME"
